In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
miles=pd.DataFrame({"farthest_run_mi":[50,62,np.nan,100,26,13,31,50]})

In [4]:
miles

   farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [5]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
imp_mean=SimpleImputer(strategy='mean').set_output(transform='pandas')

In [32]:
imp_mean

SimpleImputer()

In [8]:
imp_mean_transform=imp_mean.fit_transform(miles)

In [9]:
imp_mean_transform

   farthest_run_mi
0        50.000000
1        62.000000
2        47.428571
3       100.000000
4        26.000000
5        13.000000
6        31.000000
7        50.000000

In [28]:
imp_mean_marked=SimpleImputer(strategy='mean',add_indicator=True).set_output(transform='pandas')

In [29]:
imp_mean_marked.fit_transform(miles)

   farthest_run_mi  missingindicator_farthest_run_mi
0        50.000000                               0.0
1        62.000000                               0.0
2        47.428571                               1.0
3       100.000000                               0.0
4        26.000000                               0.0
5        13.000000                               0.0
6        31.000000                               0.0
7        50.000000                               0.0

In [12]:
#Similarly for median(strategy='median') and for mode(strategy='most_frequent')

In [13]:
names=pd.DataFrame({'names':["bibas","biswas","manish","snehashis","suvam",np.nan,"suresh"]})

In [14]:
names

       names
0      bibas
1     biswas
2     manish
3  snehashis
4      suvam
5        NaN
6     suresh

In [15]:
imp_constant=SimpleImputer(strategy='constant',fill_value="anshul")

In [16]:
imp_constant

SimpleImputer(fill_value='anshul', strategy='constant')

In [17]:
imp_constant.fit_transform(names)

array([['bibas'],
       ['biswas'],
       ['manish'],
       ['snehashis'],
       ['suvam'],
       ['anshul'],
       ['suresh']], dtype=object)

In [18]:
from sklearn.compose import make_column_transformer

In [19]:
df=pd.DataFrame({"names":["bibas","biswas","manish","snehashis","suvam",np.nan,"suresh"],"farthest_run_mi":[50,62,np.nan,100,26,13,31]})

In [20]:
df

       names  farthest_run_mi
0      bibas             50.0
1     biswas             62.0
2     manish              NaN
3  snehashis            100.0
4      suvam             26.0
5        NaN             13.0
6     suresh             31.0

In [31]:
type(df['names'])

pandas.core.series.Series

In [21]:
from sklearn.compose import make_column_transformer

In [22]:
ct=make_column_transformer(
    (imp_constant,['names']),
    (imp_mean,['farthest_run_mi']),
    remainder='drop'
)

In [23]:
ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='anshul',
                                               strategy='constant'),
                                 ['names']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [24]:
df_pandas=ct.fit_transform(df)

In [25]:
df_pandas

  simpleimputer-1__names  simpleimputer-2__farthest_run_mi
0                  bibas                              50.0
1                 biswas                              62.0
2                 manish                              47.0
3              snehashis                             100.0
4                  suvam                              26.0
5                 anshul                              13.0
6                 suresh                              31.0