In [1]:
import pandas as pd

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000], 
          'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
          'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
df=pd.DataFrame(d)

In [4]:
df.head(10)

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small
5   222222  Jacksonville  Medium
6  1111111         Miami   Large
7    20000         Miami   Small
8    75000       Orlando  Medium
9    90000       Orlando  Medium

In [5]:
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
enc=OrdinalEncoder().set_output(transform='pandas')

In [8]:
enctransform=enc.fit_transform(df[['size']])

In [9]:
enctransform

    size
0    2.0
1    1.0
2    0.0
3    0.0
4    2.0
5    1.0
6    0.0
7    2.0
8    1.0
9    1.0
10   1.0
11   2.0

In [10]:
df=df.drop(columns=['size'],axis=1)

In [11]:
df

      sales          city
0    100000         Tampa
1    222000         Tampa
2   1000000       Orlando
3    522000  Jacksonville
4    111111         Miami
5    222222  Jacksonville
6   1111111         Miami
7     20000         Miami
8     75000       Orlando
9     90000       Orlando
10  1000000       Orlando
11    10000       Orlando

In [12]:
df=pd.concat([df,enctransform],axis=1)

In [13]:
df

      sales          city  size
0    100000         Tampa   2.0
1    222000         Tampa   1.0
2   1000000       Orlando   0.0
3    522000  Jacksonville   0.0
4    111111         Miami   2.0
5    222222  Jacksonville   1.0
6   1111111         Miami   0.0
7     20000         Miami   2.0
8     75000       Orlando   1.0
9     90000       Orlando   1.0
10  1000000       Orlando   1.0
11    10000       Orlando   2.0