Feature scaling is a preprocessing step that standardizes or normalizes the numerical features in a dataset to a similar scale. Many machine learning algorithms perform better when features are on a comparable scale.

In [ ]:
#Normalisation vs Standardization

In [24]:
#Normalisation=(X-MIN(X))/MAX(X)-MIN(X) Rescales features to a fixed range (e.g., 0 to 1).
#Standardization=X-MEAN(X)/STD (Transforms data to have mean = 0 and standard deviation = 1.) it is helpful when dealing with outliers.

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("500hits.csv",encoding='latin-1')

In [5]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [6]:
df=df.drop(columns=['PLAYER','CS'])

In [7]:
df.info

<bound method DataFrame.info of      YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB  \
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315
463   16  1822   6309   714  1660  254   25   54   593   396   489   74
464   15  1468   5629   785  1660  247   71   61   499   266   471  267

        BA  HOF
0    0.366    1
1    0.331    1
2    0.345    1
3    0.310    1
4    0.329    1
..     ...  ...
460  0.250    0
461  0.273    0
462  0.256    0
463  0.263    0
464  0.295    0

[465 rows x 14 columns]>

In [8]:
df.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,17.049,2048.699,7511.456,1150.314,2170.247,380.953,78.555,201.049,894.260,783.561,847.471,195.905,0.289,0.329
std,2.765,354.392,1294.066,289.635,424.191,96.483,49.363,143.623,486.193,327.432,489.224,181.846,0.021,0.475
min,11.000,1331.000,4981.000,601.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.246,0.000
25%,15.000,1802.000,6523.000,936.000,1838.000,312.000,41.000,79.000,640.000,535.000,436.000,63.000,0.273,0.000
50%,17.000,1993.000,7241.000,1104.000,2076.000,366.000,67.000,178.000,968.000,736.000,825.000,137.000,0.287,0.000
75%,19.000,2247.000,8180.000,1296.000,2375.000,436.000,107.000,292.000,1206.000,955.000,1226.000,285.000,0.300,1.000
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,2597.000,1406.000,0.366,2.000

In [9]:
X1=df.iloc[:,0:13]

In [10]:
X2=df.iloc[:,0:13]

In [11]:
X1

     YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225  0.250
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20  0.273
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315  0.256
463   16  1822   6309   714  1660  254   25   54   593   396   489   74  0.263
464   15  1468   5629   785  1660  247   71   61   499   266   471  267  0.295

[465 rows x 13 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaleStandard=StandardScaler()

In [14]:
X1=scaleStandard.fit_transform(X1)

In [15]:
X1=pd.DataFrame(X1,columns=['YRS','G','AB','R','H','2B','3B','HR','RBI','BB','SO','SB','BA'])

In [16]:
X1

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,3.648290
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,1.996159
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,2.657012
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,1.004881
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,1.901752
...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,-0.741964,-0.363545,-0.664093,-0.156620,-1.192368,-0.995570,-0.802168,0.626972,0.143595,1.346579,1.185863,0.160169,-1.827343
461,-0.017907,-0.620600,-1.098077,-0.865170,-1.194728,-0.020260,-1.390285,0.515449,0.351555,0.466060,1.239066,-0.968376,-0.741657
462,-0.741964,-0.606476,-0.783226,-0.305243,-1.201808,-0.445661,-0.234331,0.062387,-0.274384,0.539436,0.700901,0.655627,-1.544120
463,-0.379936,-0.640373,-0.930208,-1.508049,-1.204168,-1.317215,-1.086086,-1.024962,-0.620298,-1.184914,-0.733523,-0.671101,-1.213694
464,-0.741964,-1.640344,-1.456250,-1.262649,-1.204168,-1.389844,-0.153211,-0.976171,-0.813845,-1.582371,-0.770355,0.391383,0.296825

In [17]:
X1.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,-0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,0.000,0.000,-0.000,0.000,0.000
std,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001
min,-2.190,-2.027,-1.958,-1.899,-1.204,-2.116,-1.532,-1.339,-1.841,-1.665,-1.734,-1.040,-2.016
25%,-0.742,-0.697,-0.765,-0.741,-0.784,-0.715,-0.762,-0.851,-0.524,-0.760,-0.842,-0.732,-0.742
50%,-0.018,-0.157,-0.209,-0.160,-0.222,-0.155,-0.234,-0.161,0.152,-0.145,-0.046,-0.324,-0.081
75%,0.706,0.560,0.517,0.504,0.483,0.571,0.577,0.634,0.642,0.524,0.775,0.490,0.533
max,3.240,3.557,3.754,3.956,4.764,4.265,4.673,3.861,2.888,4.300,3.580,6.662,3.648

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
scaleMinMax=MinMaxScaler(feature_range=(1,2))
#feature_range=(a, b) → Transforms features to the range [a, b].

In [35]:
X2=scaleMinMax.fit_transform(X2)

In [36]:
X2=pd.DataFrame(X2,columns=['YRS','G','AB','R','H','2B','3B','HR','RBI','BB','SO','SB','BA'])

In [37]:
X2.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,1.866667,1.861912,1.874035,1.971074,2.000000,1.889431,1.954248,1.144772,1.316064,1.517683,1.137466,1.632595,2.000000
1,1.733333,1.857360,1.811459,1.795750,1.778964,1.891057,1.568627,1.624665,1.849369,1.697078,1.268002,1.050751,1.708333
2,1.733333,1.737481,1.706217,1.756198,1.733096,2.000000,1.715686,1.144772,1.315194,1.585341,1.084713,1.303788,1.825000
3,1.600000,1.716237,1.841663,1.780401,1.713721,1.596748,1.205882,1.336461,1.570744,1.432086,1.708510,1.250893,1.533333
4,1.666667,1.738998,1.738047,1.670012,1.699881,1.752846,1.813725,1.123324,1.000000,1.371092,1.125915,1.511079,1.691667

In [23]:
X2.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,0.403,0.363,0.343,0.324,0.202,0.332,0.247,0.257,0.389,0.279,0.326,0.135,0.356
std,0.184,0.179,0.175,0.171,0.168,0.157,0.161,0.193,0.212,0.168,0.188,0.130,0.177
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.267,0.238,0.209,0.198,0.070,0.220,0.124,0.094,0.279,0.152,0.168,0.040,0.225
50%,0.400,0.335,0.306,0.297,0.164,0.307,0.209,0.227,0.421,0.255,0.318,0.093,0.342
75%,0.533,0.463,0.433,0.410,0.283,0.421,0.340,0.379,0.525,0.367,0.472,0.199,0.450
max,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000

✅ n_features = Number of input variables (used in ML models).
✅ n_columns = Number of DataFrame columns (may include non-features).

Before: Splitting data (to avoid data leakage).
After: Handling missing values & outliers.
During: Preprocessing pipeline (using sklearn.preprocessing).